# @package _global_
defaults:
  - ../base
  - /loggers@loggers.wandb: wandb
  - /loggers@loggers.csv: csv
  - _self_

seed: 112
experiment_name: jerex/doc_red_distant

runner:
  _target_: memory_re.models.jerex.runner.train

data:
  neg_mention_count: 200
  neg_coref_count: 200
  neg_relation_count: 200
  max_span_size: 10
  lowercase: false

dataset_name: DistantDocREDRelationExtractionDataset

model:
  model_type: joint_multi_instance
  meta_embedding_size: 45
  size_embeddings_count: 35
  position_embeddings_count: 750

trainer:
  max_epochs: 1

saved_pretrained_model_name: jerex_multi_instance_distant_doc_red
