# @package _global_
defaults:
  - ./base
  - /loggers@loggers.wandb: wandb
  - /loggers@loggers.csv: csv
  - _self_
  - override /artifacts_tracking: multirun

seed: 112

runner:
  _target_: memory_re.models.jerex.runner.train
